### ISSUE TITLE
[FEATURE REQUEST] Option to combine Bed Detection into 1 Deterctor

### ISSUE THREAD

**Issue by derfx4** [DeeeeLAN/homebridge-sleepiq#10]
It would be good to set an option or a 3rd motion detection for when both the LEFT and RIGHT sides are occupied.  With the way Homekit is designed, if someone wanted to create an automation when both LEFT and RIGHT sides are occupied, you are unable to do this today.

An option that looks for LEFT and RIGHT to be occupied at the same time and then respond with MOTION DETECTED would allow for this.

Thanks!!

**Comment by DeeeeLAN** [comment]
While the home app is not capable of this configuration, it does appear that HomeKit itself is capable. I just tested it in home( by brutella) and I was able to configure multiple sensors as an automation trigger. I don't know if it is reliable, but that may be worth looking into. 
![file-1](https://user-images.githubusercontent.com/12877032/60037829-88a7b180-9667-11e9-8043-45f89973035d.jpeg)

**Comment by DeeeeLAN** [comment]
Thanks for the help, @digicide

**Comment by Ducky6944** [comment]
Would it be possible to get a both sides sensor in addition to any side? Effectively what I am trying to do is turn off a set of lights if both sides are occupied and turn on a set of lights if either side is unoccupied. I tried using the Home app you mentioned above, but it doesn't seem to work for me. @DeeeeLAN

**Comment by DeeeeLAN** [comment]
I can get one added, but here is what I have configured to do exactly what you are proposing, how did you set u the automations? 
![55845E55-5A88-4356-A05B-A07238D3C372](https://user-images.githubusercontent.com/12877032/96074968-d77de980-0e5e-11eb-86f6-34a06736f027.jpeg)
![5313DCBE-B8B3-4A5E-8C63-4AEA1E242692](https://user-images.githubusercontent.com/12877032/96074970-d947ad00-0e5e-11eb-9533-b85a22b138d3.jpeg)

Just make a unified one that requires both to turn it on, then two separate ones to turn it off.

**Comment by Ducky6944** [comment]
@DeeeeLAN This is effectively verbatim what I have configured the only difference is that I set it to work from 2130 to 0700. This seems to break the automation for me. It seems like a problem with the Home+ app and I tweeted the developer about it. Removing the Time of Day works. 

[screenshot of what breaks the automation](https://imgur.com/a/UDLqBy9)

**Comment by DeeeeLAN** [comment]
Okay, now this ticket is done for real. You should now have an "any side" sensor and a "both sides" sensor.

**Comment by Ducky6944** [comment]
> Okay, now this ticket is done for real. You should now have an "any side" sensor and a "both sides" sensor.

A real life hero. Thanks!

**Comment by Ducky6944** [comment]
@DeeeeLAN No rush, but could you push this to NPM so Homebridge can pick this up?

**Comment by DeeeeLAN** [comment]
Sorry about that, I thought I did that but I guess I forgot. It is up now.

**Comment by Ducky6944** [comment]
No worries and thanks!
