### ISSUE TITLE
Sleep Number Dual Temp

### ISSUE THREAD

**Issue by derfx4** [DeeeeLAN/homebridge-sleepiq#11]
Does the API set have access to the Dual Temp function?  If so would be nice to expose that as a Thermostat.

**Comment by DeeeeLAN** [comment]
Can it be controlled through the app? I don't have a dual temp layer, but I was under the impression it could only be controlled by the remote.

I have heard of a few homebridge plugins that use an IR blaster to control IR devices, so in theory a setup could be created that would allow for controlling the dual temp layer this way, but it would take a bit of investment to create.

**Comment by derfx4** [comment]
Hi, The Dual Temp can be controlled 2 ways
1) Controlled via the Controllers they come with - which they look like the main bed controller but ONLY operate the Dual Temp
2) Once setup - the main controller for the Bed can also control the Dual Temp.

It is NOT controlled via IR.  However, thinking through this and with your question, Im assuming it may be bluetooth or other RF possibly as it cannot be controlled through the APP - which leads me to think that there are no APIs.

**Comment by DeeeeLAN** [comment]
Yes, unfortunately without some serious reverse engineering (RF may be possible, Bluetooth not so much), it won’t be simple to do. The best we can hope is they eventually release a dual temp layer that can be controlled through the app.
