### ISSUE TITLE
Causes issue with multiple instances of Homebridge

### ISSUE THREAD

**Issue by QuantumR53** [DeeeeLAN/homebridge-sleepiq#12]
When using multiple instances of Homebridge the SleepIQ plugin will cause all the instances of Homebridge, except the specific one which it is configured for, to fail to load due to lack of configuration parameters in the config.json files instead of ignoring the plugin in all other instances like other plugins (ex. homebridge-harmonyhub is one which specifically ignores all other instances except the one it is configured for).

**Comment by DeeeeLAN** [comment]
Thanks, I will get that fixed tonight.

**Comment by DeeeeLAN** [comment]
Okay, it should be fixed in version 3.2.10. Let me know if you have any issues.

**Comment by QuantumR53** [comment]
Works perfectly, thanks!
