### ISSUE TITLE
[FEATURE REQUEST] Bed inflation percent complete

### ISSUE THREAD

**Issue by 400HPMustang** [DeeeeLAN/homebridge-sleepiq#14]
Let me preface this by saying I'm not even sure if this is possible given the way homekit works but here goes:

Current behavior: Set sleep number (bulb) to desired percentage e.g 50% and the bed will adjust but the sleep number in homekit is always represented as the end result

Desired behavior: Set sleep number (bulb) to desired percentage e.g 50% and the bed will adjust, when the sleep number API reports back the inflation status display the current status on the bulb so that the user can identify whether or not inflation is complete instead of waiting for a period of time assume bed adjustment is complete.

**Comment by DeeeeLAN** [comment]
Hmm, I don't know if I could get this to work reliably. In theory, the slider should display whatever value is read from the bed, but it only updates every few seconds. I am not sure its behavior during adjusting. The number should automatically readjust to whatever the bed is reading at, but I don't know if that is working reliably or not either.

**Comment by 400HPMustang** [comment]
The number just shows the final end result during the entire inflating/deflating process so if I'm at 50% and go to 100% all I see is 100% on screen while it's adjusting where as with the native app and the remote it shows the current status as it changes. If it's not possible no worries.

**Comment by DeeeeLAN** [comment]
My current understanding of Homekit/Homebridge says that this isn't something I could do, but I might be wrong. I would be curious how other slow moving things are handled natively in HomeKit, like curtains. If they track the current value, then there is hope for us too.
