### ISSUE TITLE
Error Code :418 and Error Code :503

### ISSUE THREAD

**Issue by 400HPMustang** [DeeeeLAN/homebridge-sleepiq#16]
[[10:27:2019] | SleepNumber.txt](https://github.com/DeeeeLAN/homebridge-sleepiq/files/3779862/10.27.2019.SleepNumber.txt)

Had these happening yesterday afternoon, I couldn't figure out why homebridge would stop running after a few minutes. I checked the iOS app and Sleep Number was having some sort of issue at the same time I was getting the log errors. Looks like if the Sleep Number API is unavailable homebridge is just quitting. Not sure if this is something that could be handled, this is the first time it's happened so I thought I'd share since it's data.

![IMG_5097](https://user-images.githubusercontent.com/45641587/67701131-64ddda80-f97d-11e9-8a06-96ab32f16693.PNG)

**Comment by rob74lee** [comment]
I had a similar issue and I uninstalled the plugin until this has been resolved.

**Comment by 400HPMustang** [comment]
FWIW I haven't had this issue since I first reported it.
