### ISSUE TITLE
separate sensor for humidity to use in automation?

### ISSUE THREAD

**Issue by fabriziorizzo** [DeeeeLAN/homebridge-sleepiq#18]
Currently, only "Air Quality" seems available in the Accessory Automation portion of the Apple Home app.  It would be useful to be able to automate based on the humidity sensor too in order to control other plugs/accessories for humidifier/dehumidifiers.   Disappointed that not all sensors are exposed.

**Comment by DeeeeLAN** [comment]
Sorry, I am not sure what you mean. Does your bed have a humidity sensor on it? What model is it? I am not familiar with this feature.

**Comment by fabriziorizzo** [comment]
Sorry, wrong window/wrong project!!!!!  (it's late here and I'm out of coffee)  Sorry.
