### ISSUE TITLE
[Feature Request] Privacy Mode Switch

### ISSUE THREAD

**Issue by 400HPMustang** [DeeeeLAN/homebridge-sleepiq#2]
Is it possible for you to add a switch to turn privacy mode off or on? Use case is this:

SleepIQ tracks sleep data whenever it detects bed occupancy unless privacy mode is on. My dog will lay in bed when we're not home, causing SleepIQ to believe I am in bed sleeping when I am not. 

I would like to be able to automate privacy mode on for when I am not home and then off when I am ready for bed.

Thank you!

**Comment by DeeeeLAN** [comment]
yes, that should be trivial to get added.

**Comment by DeeeeLAN** [comment]
Resolve in 438c8e2.
