### ISSUE TITLE
Foot warmer API in flex fit 3 base

### ISSUE THREAD

**Issue by rvrolyk** [DeeeeLAN/homebridge-sleepiq#22]
Hi there,

I don't actually use your plugin but it was referenced in a Hubitat thread and your note of using a proxy on Android made me realize I can sniff out what the foot warmer API is.  Since I notice it's in your future enhancements, I wanted to share.  Please see https://community.hubitat.com/t/sleepiq-sleep-number/15053/83?u=rvrolyk for the details and let me know if you have any questions I can help answer.

**Comment by DeeeeLAN** [comment]
Thanks, I might be able to use that!

**Comment by DeeeeLAN** [comment]
@rvrolyk Do you have to set a timer, or can you leave it on?

**Comment by rvrolyk** [comment]
As far as I can tell, a timer is required.

**Comment by DeeeeLAN** [comment]
Is there a tempRight and a tempLeft field in the same dataset, or are they separate calls?

**Comment by DeeeeLAN** [comment]
Initial attempt added in 5b72427.

**Comment by rvrolyk** [comment]
I think that won't work as written.  The API SleepNumber exposes is a bit clunkier... the status call you have works but the request on line 573 needs to be structured like:

```
{
  _k: key,
 footWarmingTempRight: tempRight,
 footWarmingTimerRight: timerRight,
 footWarmingTempLeft: tempLeft,
 footWarmingTimerLeft: timerLeft
}
```

I tested and though their app only ever sends a single side at a time, the API will let you send all four parameters

**Comment by DeeeeLAN** [comment]
I wish they could have some consistency in their different endpoints. Can you try with the style I have written? I am curious if it will work anyway, since they use that style for so many of their requests. Maybe we will get lucky and they accept multiple styles.

**Comment by rvrolyk** [comment]
Unfortunately that fails with a BadRequest response.  Agree it would be
nice if they were more consistent... though I'd settle for a fully
supported public API :)

**Comment by DeeeeLAN** [comment]
Okay, I just pushed an update that should work. We will see once somebody tests it, but I believe it should follow the correct format now.
