### ISSUE TITLE
Single head / Single Foot Flex base

### ISSUE THREAD

**Issue by randymassey** [DeeeeLAN/homebridge-sleepiq#30]
I have been using the plugin for a few months & see the recent changes (nice plugin thank you BTW).  I see you also need some help from people with Flex Bases.  I have been having some issues between the recent updates, oh & I did recently see the foot heaters appear, nice..  Issue tho,I notice after this plugin updates, if you next just reboot HOOBS, it will reboot, but then shutdown the entire HOOBS server into Stop status, & in the log it ends up being a problem with communication to the Flex Base foundation, so I have to power cycle the bed, & then HOOBS will be able to successfully run upon another reboot of HOOBS, but as of now (unless it should do this), post this plugin UD, it shuts down, not just the SleepIQ plugin, but all of HOOBS cannot "start services" & if you try a reboot it will fail out & stop services.  I do have an IT background & am (long ago) out of a development environment (testing, not programming), so can help a bit as well, but my time is a little constrained ATM, I do like controlling the bed this way.  Tho it seems a tad off that changes to this plugin would shut down all of HOOBS until you power cycle the bed / foundation, so I can of course grab some logging too if relevant.

Thought I would check in & offer to help in whatever way I can.

Randy

**Comment by DeeeeLAN** [comment]
Try updating to 4.1.13, I just fixed a bug that was causing homebridge to restart. I don't know why the base would need to be reset, I haven't seen that before. If you are still having issues after updating, please share some debug logs and I will see what I can do.

**Comment by randymassey** [comment]
Ok, I will do that & report back...

An UD will be a perfect test.

RM

**Comment by DeeeeLAN** [comment]
V4.1.16 (the latest version) should fix all your issues, it has been reported to be functioning without any problem.

**Comment by randymassey** [comment]
Yes, the crashing of HOOBS post plugin UD & then reboot of HOOBS has been resolved in the subsequent plugin updates you pushed, tho I did have it crash last night & the log was full of errors relating to the bed, it seems around 4:30AM it could no longer talk to the foundation of the bed & that crashed HOOBS & stopped Bridge services, (I was not able to grab the logs unfortunately), there have been subsequent plugin updates from you since that install, so I did update, & I am needing a day or two to test.

**Comment by DeeeeLAN** [comment]
Okay, let me know.
