### ISSUE TITLE
getting Cannot read property 'isInBed' of null warnings

### ISSUE THREAD

**Issue by keokoa** [DeeeeLAN/homebridge-sleepiq#35]
(node:1705) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isInBed' of null

anybody know how to fix this?

**Comment by DeeeeLAN** [comment]
I will need more information. Can you post a full debug log? What bed/base combo do you have?

**Comment by keokoa** [comment]
9/29/2020, 8:39:33 PM HOOBS listening on port 80.
9/29/2020, 8:40:38 PM Loaded plugin "homebridge-sleepiq".
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0privacy UUID:  6aa50730-2659-42b7-8fbb-64b33cc3cce7
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0leftSideoccupancy UUID:  4b06eb7a-b269-45b9-8442-e55b121edbe9
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0leftSidenumber UUID:  e7025bc5-3bba-417e-aa57-8fbbcc28966e
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0leftSideflex UUID:  13326cf3-a91e-49ff-b0ec-a68289fff620
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0leftSideoutlet UUID:  950dd11e-c28b-4f1f-a5a4-90c7354b6962
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0leftSidelightstrip UUID:  44c4e2f7-7d77-493b-b566-818df6a0e339
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0rightSideoccupancy UUID:  c5cb3ba6-4ce6-45cb-b425-9f369e2e124a
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0rightSidenumber UUID:  12624ad5-82b5-47f7-9b38-9bcb56023f43
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0rightSideflex UUID:  72af8c32-019d-4977-a7d7-511e933d2aee
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0rightSideoutlet UUID:  f9841500-345c-430d-bf35-ca46b19485a1
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0rightSidelightstrip UUID:  43dcbf69-ecd1-4f50-b5e5-055a17e3f86b
9/29/2020, 8:40:38 PM [SleepIQ] Configuring Cached Accessory:  bed0anySideoccupancy UUID:  f83b7e00-f928-440b-ab96-af2884f2bbfa
9/29/2020, 8:40:39 PM Bridge is running on port 51826.
9/29/2020, 8:40:49 PM [SleepIQ] No foot warmer detected
9/29/2020, 8:40:49 PM [SleepIQ] bed0 privacy already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0leftSide occupancy already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0leftSide number control already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0leftSide flex foundation already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0leftSide outlet already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0leftSide lightstrip already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0rightSide occupancy already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0rightSide number control already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0rightSide flex foundation already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0rightSide outlet already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0rightSide lightstrip already added from cache
9/29/2020, 8:40:49 PM [SleepIQ] bed0anySide occupancy already added from cache
9/29/2020, 8:40:49 PM (node:1058) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isInBed' of null
9/29/2020, 8:40:49 PM at SleepIQPlatform.<anonymous> (/root/.hoobs/node_modules/homebridge-sleepiq/index.js:722:53)
9/29/2020, 8:40:49 PM at Array.forEach (<anonymous>)
9/29/2020, 8:40:49 PM at SleepIQPlatform.<anonymous> (/root/.hoobs/node_modules/homebridge-sleepiq/index.js:712:30)
9/29/2020, 8:40:49 PM at processTicksAndRejections (internal/process/task_queues.js:97:5)
9/29/2020, 8:40:49 PM (node:1058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

c4 w/SIQ and Queen FlexFit1

**Comment by keokoa** [comment]
[logs.txt](https://github.com/DeeeeLAN/homebridge-sleepiq/files/5303068/logs.txt)

I have a c4 w/SIQ bed and Queen FlexFit1 base

**Comment by keokoa** [comment]
So how do I fix this?

**Comment by DeeeeLAN** [comment]
I need a debug log, that is a standard log. I need to see the contents of the API calls so I can figure out why your bed is not providing the isInBed field.

**Comment by keokoa** [comment]
How do I get the debug log on a Hoobs in a box?

**Comment by DeeeeLAN** [comment]
I have not used hoobs, I am not sure. I know in Homebridge UI there is a toggle for it in settings.

**Comment by keokoa** [comment]
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
[HOOBS] Stopping server.
root@hoobs:/root/.hoobs/etc#

**Comment by DeeeeLAN** [comment]
Make sure you stop your first instance, or select a different port. Something is already running on port 80 so you can't run a second thing on the same port.

**Comment by keokoa** [comment]
root@hoobs:/root/.hoobs/etc# hoobs -d
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080
}
/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs bridge -u /root/.hoobs/etc -p /root/.hoobs/node_modules -r -d
[HOOBS] Stopping server.
root@hoobs:/root/.hoobs/etc# 

I changed the port and this what I get

**Comment by keokoa** [comment]
I don't know how else to get the information you asking for

**Comment by DeeeeLAN** [comment]
You will need to reach out to the HOOBS developers for support. I have not used it so I can't do much to help. Once you get the debug logs I can continue assisting.
