### ISSUE TITLE
Occupancy Appears in Homebridge But Not in Home App

### ISSUE THREAD

**Issue by turnepf** [DeeeeLAN/homebridge-sleepiq#37]
I can see occupancy for each side of my bed in the homebridge interface, but it doesn't appear in the home app (that I can find.) Am I missing something? (Not really an issue so much as a question.)

Thanks!

**Comment by DeeeeLAN** [comment]
It shows up fine for me and I haven't seen anybody else report this. Maybe try removing and re-adding the instance? Check for a default room somewhere as well that maybe the devices added up in. If you go to the home app settings, there should be a place you can view bridges, and if you click on it it will show you all the devices associated with the bridge. You can check there as well.

**Comment by turnepf** [comment]
Good call. Thanks @DeeeeLAN
