### ISSUE TITLE
This plugin has been disabled.

### ISSUE THREAD

**Issue by DeeeeLAN** [DeeeeLAN/homebridge-sleepiq#38]
In my original readme, I had a statement: 

> So far, I have not seen Sleep Number get upset with too many requests, but in theory they could at some point in time if we flood their network.

Unfortunately, that day has come. I received a call from Sleep Number requesting I take down this plugin as it is overwhelming their network and making the SleepIQ experience worse for everybody, and it is a direct violation of their User Agreement. This update removes all functionality (you will need to remove the accessories from HomeKit). If you choose not to update, Sleep Number will likely blacklist your IP Address and reach out to you directly as they work through the list of users with massive amounts of API requests. 

I requested that they keep our small community in mind and give us a proper API with local network access in the future. I don't know if they ever will, but if they call you, please add your request to mine, make our voices heard. 

Thanks for all the good times and keep sleeping,

Dillan

**Comment by traviswparker** [comment]
Was there a problem with how frequently the requests were being made? I had mine set to 60 seconds. Even a forced minimum of 300 or 600 should be ok, how often do you really get in and out of bed?

**Comment by DeeeeLAN** [comment]
That is how they discovered the issue I believe, but they made it clear using the API in any non-official way was a breach of the User Agreement. I can’t speak to whether or not a lower ping rate would prevent them from flagging your account, and the only recommendation I can make is to uninstall the plug-in to prevent your IP address from getting blacklisted.

**Comment by 400HPMustang** [comment]
Not going to lie, I'm not nuking my install. They can call me. I'll ask again that they give us an official API and local access. There has to be local access because my phone connects do the bed via WiFi and the remotes do via BlueTooth. I honestly can't believe there's not a way to make the local access thing happen even without their support. You know know all the commands to pass to the bed there has to be a way to communicate with it locally.

**Comment by DeeeeLAN** [comment]
I have looked into hijacking the Bluetooth connection but I didn’t have any luck. You would probably need an external device to do the initial Bluetooth debug until you figured out all the necessary connections that could then be packaged up. This would have been more ideal to prevent the network issues, but we still wouldn’t be able to officially broadcast it since it breaches the user agreement. If they add an official developer API I will get this plug-in back up and running again using it. But otherwise I can’t provide any more support. Less API calls may delay the inevitable for an unknown amount of time, but I can’t recommend that. I am obligated to stick to and recommend the user agreement at this point, my hands are tied.

**Comment by 400HPMustang** [comment]
> I have looked into hijacking the Bluetooth connection but I didn’t have any luck. You would probably need an external device to do the initial Bluetooth debug until you figured out all the necessary connections that could then be packaged up. This would have been more ideal to prevent the network issues, but we still wouldn’t be able to officially broadcast it since it breaches the user agreement. If they add an official developer API I will get this plug-in back up and running again using it. But otherwise I can’t provide any more support. Less API calls may delay the inevitable for an unknown amount of time, but I can’t recommend that. I am obligated to stick to and recommend the user agreement at this point.

I completely understand the position you're in and would not ask anything of you that would put you in jeopardy. I appreciate everything you've done. Here's to hoping that they decide to listen to their customer base and decide that bricking a large number of beds is a bad idea. I've invested over $10,000 in these beds at this point and would be seriously upset at the inability to use the thing. I strictly use Siri to control my newest bed with the plugin, but I guess now I'm going to have to buy a remote in the event that they block my API access.

**Comment by traviswparker** [comment]
Want them to change? Contact the tech media. Gizmodo, Ars Technica, The Verge, etc.. or just put it on Twitter and see if it goes viral. Expose how unwilling Select Comfort is to work with us or add features. 

In these comments we have one person who has invested five figures in smart beds that are *still* missing any kind of integration in 2020, a developer that solved the problem with a handful of JavaScript, and the maker of said tech shutting down the project and threatening legal action because theIr API can’t handle what should be a considered typical load.

**Comment by vcdx71** [comment]
Well I took my chances and this morning my logs showed I couldn't connect to the sleep number servers any longer.. Seems I've been blacklisted. Bitched on twitter to them but companies this big usually don't care..

If I can help in anyway in the future please let me know, you did great work and I've enjoyed using this functionality for the past couple of years.

**Comment by 400HPMustang** [comment]
> Well I took my chances and this morning my logs showed I couldn't connect to the sleep number servers any longer.. Seems I've been blacklisted. Bitched on twitter to them but companies this big usually don't care..
> 
> If I can help in anyway in the future please let me know, you did great work and I've enjoyed using this functionality for the past couple of years.

How could you tell you were blacklisted? What state does that leave your bed in? Are you unable to control your bed now?

**Comment by vcdx71** [comment]
> > Well I took my chances and this morning my logs showed I couldn't connect to the sleep number servers any longer.. Seems I've been blacklisted. Bitched on twitter to them but companies this big usually don't care..
> > If I can help in anyway in the future please let me know, you did great work and I've enjoyed using this functionality for the past couple of years.
> 
> How could you tell you were blacklisted? What state does that leave your bed in? Are you unable to control your bed now?

Started seeing this in my logs and couldn't control my bed any longer from HomeKit. : (

```
25/11/2020, 09:56:39] [SleepIQ] Failed to authenticate with SleepIQ. Please double-check your username and password. Disabling SleepIQ plugin. Error: {"Error":{"Code":418,"Message":"Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection-CannotCreateTransactionException"}}

25/11/2020, 09:56:12] [SleepIQ] Failed to fetch foundation status: {"Error":{"Code":418,"Message":"Could not open connection; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection-DataAccessResourceFailureException"}}
[25/11/2020, 09:56:14] [SleepIQ] SleepIQ authentication failed with an unknown error code. If it persists, please report this incident at https://github.com/DeeeeLAN/homebridge-sleepiq/issues/new
[25/11/2020, 09:56:15] [SleepIQ] Unknown error occurred when checking the outlet status. See previous output for more details. If it persists, please report this incident at https://github.com/DeeeeLAN/homebridge-sleepiq/issues/new
[25/11/2020, 09:56:15] [SleepIQ] Failed to fetch outlet status: {"Error":{"Code":418,"Message":"Could not open connection; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection-DataAccessResourceFailureException"}}
[25/11/2020, 09:56:15] [SleepIQ] Unknown error occurred when checking the outlet status. See previous output for more details. If it persists, please report this incident at https://github.com/DeeeeLAN/homebridge-sleepiq/issues/new
[25/11/2020, 09:56:15] [SleepIQ] Failed to fetch outlet status: {"Error":{"Code":418,"Message":"Could not open connection; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection-DataAccessResourceFailureException"}}
[25/11/2020, 09:56:17] [SleepIQ] Unknown error occurred when checking the outlet status. See previous output for more details. If it persists, please report this incident at https://github.com/DeeeeLAN/homebridge-sleepiq/issues/new
[25/11/2020, 09:56:17] [SleepIQ] Failed to fetch lightstrip status: {"Error":{"Code":418,"Message":"Could not open connection; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection-DataAccessResourceFailureException"}}
[25/11/2020, 09:56:17] [SleepIQ] Unknown error occurred when checking the outlet status. See previous output for more details. If it persists, please report this incident at https://github.com/DeeeeLAN/homebridge-sleepiq/issues/new
[25/11/2020, 09:56:17] [SleepIQ] Failed to fetch lightstrip status: {"Error":{"Code":418,"Message":"Could not open connection; nested exception is org.hibernate.exception.JDBCConnectionException: Could not open connection-DataAccessResourceFailureException"}}
```

**Comment by brainstorm-tech** [comment]
Soon as I saw your alert i removed the plug-in. Very sad.  Would love to see SleepIQ reverse their decision and will apply gentle pressure where I can. 

Ed C.

**Comment by 400HPMustang** [comment]
Well they got me too. My phone only connects to my bed via Bluetooth now. The SleepIQ app will control my bed but throws an error on every other command and does not track sleep data anymore.

**Comment by 400HPMustang** [comment]
@vcdx71 Apparently they're just having login issues today. All their SleepIQ stuff seems to be tanking along with logging into their website. I was just on the phone and on chat with customer service both telling me the same thing. I caved and uninstalled the homebridge app though. Sad day.

**Comment by vcdx71** [comment]
> @vcdx71 Apparently they're just having login issues today. All their SleepIQ stuff seems to be tanking along with logging into their website. I was just on the phone and on chat with customer service both telling me the same thing. I caved and uninstalled the homebridge app though. Sad day.

Oh man, guess I should have waited to uninstall then... crap.. anyone happen to have a local copy they pulled?

**Comment by vcdx71** [comment]
@400HPMustang Not sure this will work for anyone else, but I went to my homebridge UI searched for the plugin and told it to install an older version picked 4.2 and it's back.. guess my pi still had it cached. Still getting auth errors but I am on their site as well so guess I wasn't blocked after all, just need to wait for them to fix their issues.

**Comment by 64Spaces** [comment]
Yes, I tried to login and no luck. I thought I might have been blocked also. I turned it off a week or so ago. Hopefully it’s just their website. Let us know if you get online.

**Comment by traviswparker** [comment]
Both the App/Plugin and the website use api.sleepnumber.com and it is currently returning
{
    "Error": {
        "Code": 418,
        "Message": "Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection-CannotCreateTransactionException"
    }
}

Looks like the backend is down. It fails before authentication so it is not a blocked account, and I've tried from different IPs so it's not an IP block.

If you are still using v4.2.0 of the plugin, _please_ set the refresh time to something 300, 600, or even 3600 until they fix their stuff. We don't want them to see us hammering their API.

**Comment by iBanks3** [comment]
I agree. May just be a server issue on their end because my SleepIQapp shows no data recorded for yesterday to today but day prior info is there. I’m also constantly getting an oops, something is wrong error popping up.

**Comment by vcdx71** [comment]
AWS is having a fairly large outage so betting that's the cause. I have the plugin disabled until I can logon again via their site.

**Comment by hbblebc** [comment]
https://github.com/hbblebc/homebridge-bed-control

**Comment by DeeeeLAN** [comment]
Please migrate to the above extension. I will be deleting this repository soon.
