### ISSUE TITLE
New? Sleep Number must be divisible by 5?

### ISSUE THREAD

**Issue by 64Spaces** [DeeeeLAN/homebridge-sleepiq#6]
I noticed the Sleep Number on my Remote now only makes changes by increments of 5. Is this new?

`{"Error":{"Code":400,"Message":"0 The sleepNumber in the request is incorrect. The sleepNumber must be between 5 and 100 and divisible by 5"}}`

**Comment by DeeeeLAN** [comment]
When I was first testing the boundaries for setting the sleep number, I didn't notice a message about being divisible by 5 (even though that is how the app works). I don't know if I just didn't notice it, or if it is a recent addition. When I was debugging some time last week I came across it. So I fixed it so the plugin takes whatever number you input from homekit and rounds it down to the nearest 5 boundary before sending it off to the sleepIQ server. Are you seeing that message on the most recent version of the plugin, or an older one? What do you mean by your remote?

**Comment by 64Spaces** [comment]
I'm running the most recent version, 3.2.9. I noticed the error in the debug log I emailed you last night. Sorry, for the remote, I mean the Sleep Number hand held Bluetooth remote that comes with the bed. I'm not sure if the SleepIQ iPhone App does the same thing, I will take a look. I think it's a recent addition. I had severed ties with the API before I discovered your plug-in. When I reconnected my system to theirs, I noticed an update to the UI and the change to increments of five.

**Comment by DeeeeLAN** [comment]
It sounds like they are enforcing it more then. And I see my error- the limit is 5 and 100, not 0 and 100. I will get that fixed.

**Comment by 64Spaces** [comment]
Thank you. In the Home App with the "light bulb" slider, it's sometimes hard to hit a specific number. The bed reacts before I finish. Scenes are fine, of course. Hopefully, it's not a big deal for the API.

**Comment by DeeeeLAN** [comment]
Yes, I have tested it, it sends multiple requests so if you continue to move it until you get the number you want, it will take the final number, overriding the old ones. And as long as you are within 5, it will round down for you, making it a little easier to hit. I am going to leave this one open until I fix the 0 issue.

**Comment by DeeeeLAN** [comment]
Should be fixed now.
