### ISSUE TITLE
Turning Bed Position to off in HomeKit

### ISSUE THREAD

**Issue by 64Spaces** [DeeeeLAN/homebridge-sleepiq#8]
When bed position is active, turning it off in HomeKit does not do anything. It has to be dimmed to zero in HomeKit.

**Comment by DeeeeLAN** [comment]
That is correct. Our beds do not have a concept of off, just completely deflated. I made the decision to have it turn right back on when turned off, instead of deflating to 0, because they are modeled as lightbulbs. So if you say  to Siri "turn off all the lights", your bed won't suddenly deflate completely. I am curious why you want to set it to 0?

**Comment by DeeeeLAN** [comment]
And actually the minimum number they support is 5 anyway, they won't let you set it all the way to 0. I think I catch that and round up to 5 when necessary, but I don't remember.

**Comment by 64Spaces** [comment]
Thank you, I was referring to the positions of the base, head and foot, when going back to flat.

**Comment by DeeeeLAN** [comment]
Oh okay, that makes more sense! Right now, I am not doing anything with the on/off case as you are seeing. I can set it so the base returns to neutral when turning them off, but the above still applies. If you tell Siri to turn off all the lights, will you want your base to change too? It might not apply to you if you don't have homekit light-bulbs all over your house like the rest of us, of course. I don't have a base so I don't know what is preferable.

**Comment by 64Spaces** [comment]
Yes, you are correct. Because of this, I put the bed into it's own room. Still easy enough for scenes, etc., but does not confuse Siri.

**Comment by DeeeeLAN** [comment]
I took a stab at implementing this, let me know if it works out for you or not.
